---

namespace_prefix: "test-project"

project:
  NAMESPACE: "{{ namespace_prefix }}"
  NAMESPACE_DISPLAY_NAME: "{{ namespace_prefix | title}}s project"

ansible_connection: local

openshift_cluster_content:
- object: projectrequest
  content:
  - name: "{{ namespace_prefix  }}-projectrequest"
    template: "{{ playbook_dir }}/templates/projects.yml"
    action: apply
    params_from_vars: "{{ project }}"
- object: resourcequota
  content:
  - name: "{{ namespace_prefix }}-resourcequota"
    namespace: "{{ namespace_prefix }}"
    template: "{{ playbook_dir }}/templates/resourcequota.yml"
    params: "{{ playbook_dir}}/params/{{ size }}"
    params_from_vars: "{{ project }}"
- object: limits
  content:
  - name: "{{ namespace_prefix }}-limits"
    namespace: "{{ namespace_prefix }}"
    template: "{{ playbook_dir }}/templates/limits.yml"
    params: "{{ playbook_dir}}/params/{{ size }}"
    params_from_vars: "{{ project }}"

# When the ocp_templates gets moved to cop land we can merge the two raws below
openshift_templates_raw: "https://raw.githubusercontent.com/rht-labs/openshift-templates"
openshift_templates_raw_version_tag: "v1.4.9"
cop_quickstarts: "https://github.com/redhat-cop/containers-quickstarts.git"
cop_quickstarts_raw: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts"
cop_quickstarts_raw_version_tag: "v1.9"
