---
- name: Provision new namespaces with specific resources
  hosts: all
  connection: local
  tasks:

    - name: Login to the OCP Cluster
      shell: "oc login --token={{ api_key }}"
      #when:
      #  - api_key is defined

    - include_role:
        name: openshift-applier/roles/openshift-applier
