---
apiVersion: v1
kind: Template
metadata:
  name: limitrange
objects:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: ${NAMESPACE}-limits
    creationTimestamp: null
  spec:
    limits:
      -
        type: Container
        max:
          cpu: 4000m
          memory: 1024Mi
        min:
          cpu: 10m
          memory: 5Mi
        default:
          cpu: 4000m
          memory: 1024Mi
        defaultRequest:
          cpu: 100m
          memory: 512Mi
parameters:
- description: Name
  displayName: Name
  name: NAMESPACE
  required: true

